### ISSUE TITLE
Html /CSS diagnostics

### ISSUE THREAD

**Issue by bragmore** [hrsh7th/vscode-langservers-extracted#5]
Im looking everywhere for diagnostics for html CSS without any hassle or setup for nvim. No stylua or anything like that. Will this give me diagnostics for both CSS and html? I tried installing the lsp via lsp install but that might be using anything else. Thanks alot!

**Comment by hrsh7th** [comment]
Are you using the LSP plugin?

**Comment by bragjo** [comment]
> Are you using the LSP plugin?

I am using lspconfig. Together with lsp install plugin Looked everywhere for a solution for linting html without having to create json files for both CSS and html for every project. I just want it to work. Like for many other languages.

**Comment by captainko** [comment]
Hi @bragjo, you can pass options to the format method like the example below.

```lua
local u = require "lspconfig/util"

local format_opt = {
  wrapAttributes = "force-aligned",
  -- tabSize?: number;
  --  insertSpaces?: boolean;
  --  indentEmptyLines?: boolean;
  --  wrapLineLength?: number;
  --  unformatted?: string;
  --  contentUnformatted?: string;
  --  indentInnerHtml?: boolean;
  --  wrapAttributes?: 'auto' | 'force' | 'force-aligned' | 'force-expand-multiline' | 'aligned-multiple' | 'preserve' | 'preserve-aligned';
  --  wrapAttributesIndentSize?: number;
  --  preserveNewLines?: boolean;
  --  maxPreserveNewLines?: number;
  --  indentHandlebars?: boolean;
  --  endWithNewline?: boolean;
  --  extraLiners?: string;
  --  indentScripts?: 'keep' | 'separate' | 'normal';
  --  templating?: boolean;
  --  unformattedContentDelimiter?: string;
}

local function format()
  return vim.lsp.buf.formatting(vim.tbl_extend("keep", {}, format_opt))
end

local function range_format()
  return vim.lsp.buf.range_formatting(vim.tbl_extend("keep", {}, format_opt))
end

local function formatting_sync()
  return vim.lsp.buf.formatting_sync(vim.tbl_extend("keep", {}, format_opt))
end

vim.g.html_format = format_opt

```
My config file [captainko/ckovim](https://github.com/captainko/ckovim/blob/70d09e50320de74fb3f9b9314e2e9cf70d570f86/lua/cko/lsp/html.lua)

**Comment by bragjo** [comment]
@hrsh7th did u find anything regarding this?

**Comment by hrsh7th** [comment]
I've updated language servers.

Sorry. I can't support this servers. I'm only extracting it.
