### ISSUE TITLE
The language servers dont work?

### ISSUE THREAD

**Issue by MordechaiHadad** [hrsh7th/vscode-langservers-extracted#6]
Basically when installing the servers
via lspinstall or manually the servers are attached but I and other folks don't get completion for some reason?

**Comment by captainko** [comment]
I think you properly mean the CSS doesn't provide any completion item. In that case, you should go and take a look at the isp config for  [cssl-config](https://github.com/neovim/nvim-lspconfig/blob/a0086f6ce80e4de8f441d073570b68612dc7d83b/lua/lspconfig/cssls.lua#L38). All you need is to enable `snippetSupport`.

**Comment by MordechaiHadad** [comment]
> 
> 
> @MordechaiHadad I think you properly mean the CSS doesn't provide any completion item. In that case, you should go and take a look at the lsp config for [cssls](https://github.com/neovim/nvim-lspconfig/blob/a0086f6ce80e4de8f441d073570b68612dc7d83b/lua/lspconfig/cssls.lua#L38). All you need is to enable `snippetSupport`.

Doesn't work for all of the vscode lsps that need snippetSupport

**Comment by MordechaiHadad** [comment]
Never mind found the issue
